Change the way modules are started.
Modules will now ALL call init() BEFORE the run() is called. This means that if we want to change something in another module we can. Example case, music module adding a listener to the DefaultShardManagerBuilder.

* Classes will now override rather than just getting the cached one, this is an attempt to fix issues with NoSuchMethodError's, we will see how this performs in the long run.
* STARTING and STARTED is now INITIALISING and INITIALISED to better show the status of the modules.